version: '3.8'

services:
  web:
    build: ./
    container_name: di_inter_tech_2025_php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - composer
      - db
    networks:
      - di_internet_technologies_network

  composer:
    image: composer:latest
    platform: linux/amd64    
    container_name: di_inter_tech_2025_composer
    volumes:
      - ./php:/app
    working_dir: /app
    command: ["composer", "install"]

  db:
    image: mysql:8.0.28
    platform: linux/amd64    
    container_name: di_inter_tech_2025_mysql
    environment:
      - MYSQL_HOST=
      - MYSQL_DATABASE=di_internet_technologies_project
      - MYSQL_USER=webuser
      - MYSQL_PASSWORD=webpass
      - MYSQL_ROOT_PASSWORD=rootpass
      - TZ=EEST
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/:ro
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:33306:3306"
    networks:
      - di_internet_technologies_network

networks:
  di_internet_technologies_network:
    name: di_internet_technologies_network
    driver: bridge
